serviceAccount:
  name: appointment-ui-dev-service-account

image:
  tag: 1.1.2

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: appointment-ui.local
      paths:
        - path: /
          pathType: Prefix

configMap:
  fileName: environment-dev.json